name: Generate Release (after signing)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      ### NOTE: This workflow continues the "Generate Release" workflow if it timed out.

      - name: Firefox — Download Latest Signed XPI
        run: node dev/download_signed_xpi.mjs
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - name: Get Release Version
        uses: actions/github-script@v8
        id: get-version
        with:
          result-encoding: string
          script: |
            const fs = require('node:fs');
            const { version } = JSON.parse(fs.readFileSync(('${{ github.workspace }}/src/manifest.json')));
            const files = fs
              .readdirSync('${{ github.workspace }}/web-ext-artifacts')
              .filter(filePath => filePath.endsWith(`${version}.xpi`));
            if (files.length === 0) {
              throw new Error(`Could not find signed v${version} XPI! Has Mozilla reviewed it?`);
            }
            const releases = await github.paginate(github.rest.repos.listReleases, { owner: context.repo.owner, repo: context.repo.repo, });
            if (releases.some(({ tag_name }) => tag_name === `v${version}`)) {
              throw new Error(`Release v${version} already exists! Did you forget to bump the manifest.json version?`);
            }
            return version;

      - name: Create Github release draft
        uses: softprops/action-gh-release@v2
        with:
          name: Tumblr Resize ${{ steps.get-version.outputs.result }}
          tag_name: v${{ steps.get-version.outputs.result }}
          body: |
            <!-- -->
          files: web-ext-artifacts/*.xpi
          draft: true
